# Generated by Django 5.0.4 on 2024-10-23 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='book_covers/'),
        ),
    ]
